### ISSUE TITLE
Versioning on Docker Hub

### ISSUE THREAD

**Issue by JamesBarwell** [joshbalfour/docker-cloudwatch-logs#1]
Hi, would it be possible please to configure the Docker Hub automated build so as to provide versioned tags for the images, rather than just overwriting 'latest' each time? We'd like to use this, but don't want to always be pulling the latest build. Cheers.

**Comment by joshbalfour** [comment]
@JamesBarwell hey, sounds like a great idea, I'll look into it and get back to you here

**Comment by JamesBarwell** [comment]
In case it helps, here's my config on Docker Hub for one of my automated builds:

![dockerhub_autobuild_settings](https://cloud.githubusercontent.com/assets/640223/25656511/46f90f06-2ff1-11e7-8cf3-710dac005832.png)

So this will do a 'latest' tag build for any updates to the master branch, plus an additional versioned build whenever it sees a tag with numbers and dots.

If you set up an automated build linked to this Git Hub account, all you'd need to do after in this repo is the relevant tagging and push everything each time you want a new build:
```
git commit -m "latest stuff"
git tag 1.2.3
git push && git push --tags
```

**Comment by joshbalfour** [comment]
@JamesBarwell thank you so much for your help!
This seems to have worked: https://hub.docker.com/r/joshbalfour/cloudwatch-logs/tags/

**Comment by JamesBarwell** [comment]
That's great, cheers for getting it sorted so quickly. As it happens I'm actually working on some log forwarding today so I can immediately start using it!
